### ISSUE TITLE
CPU占用异常

### ISSUE THREAD

**Issue by CLtheorem** [huww98/dsp_blueprint_editor#10]
我这边打开页面https://huww98.github.io/dsp_blueprint_editor/ CPU占用就会拉满，有明显的卡顿感，打开控制台暂停js代码后CPU占用就下来了，应该是js逻辑有问题。
我记得1年多前用的时候没这个问题，是不是更新出bug了，希望大佬有时间看看。

**Comment by huww98** [comment]
这个应用按理不怎么吃CPU。但因为有大量的渲染，所以打开大的蓝图时GPU压力会比较大，同时你屏幕刷新率越高，压力越大，因为渲染帧率是浏览器自动根据屏幕刷新率确定的。你暂停js后同时也暂停了动画更新，GPU也不会渲染了。我刚刚测试了一个4万建筑的蓝图，CPU也是非常空闲的。
![image](https://github.com/user-attachments/assets/722058ab-4ea8-481d-8642-893b7be8ca59)

你也可以用chrome的performance功能看看是哪里的瓶颈。另外，笔记本的话，建议试试用用独立显卡打开浏览器，以获取最好的性能。

**Comment by CLtheorem** [comment]
> 这个应用按理不怎么吃CPU。但因为有大量的渲染，所以打开大的蓝图时GPU压力会比较大，同时你屏幕刷新率越高，压力越大，因为渲染帧率是浏览器自动根据屏幕刷新率确定的。你暂停js后同时也暂停了动画更新，GPU也不会渲染了。我刚刚测试了一个4万建筑的蓝图，CPU也是非常空闲的。 ![image](https://private-user-images.githubusercontent.com/15710934/369662587-722058ab-4ea8-481d-8642-893b7be8ca59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTQzNjUsIm5iZiI6MTcyNzAxNDA2NSwicGF0aCI6Ii8xNTcxMDkzNC8zNjk2NjI1ODctNzIyMDU4YWItNGVhOC00ODFkLTg2NDItODkzYjdiZThjYTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDE0MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NDhlYjczNWE0ZWIyZDhlZDE5MzBkYjZhNTI2NjRjZGZhOGQ0MmZjNjI1NjdkMWM4OGQ3NmZkYjZkNDA4OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pNlH_K7MOxyYJxCB9LcEWxogd3Flc5KwgCu83U1myyE)
> 
> 你也可以用chrome的performance功能看看是哪里的瓶颈。另外，笔记本的话，建议试试用用独立显卡打开浏览器，以获取最好的性能。

![2024-09-22_221646](https://github.com/user-attachments/assets/846b903b-d023-4d9c-9371-606d4b1d8cf8)
我chrome设置的是使用独立显卡，但他看起来是在用cpu进行渲染- -

**Comment by huww98** [comment]
可以提供下你测试用的蓝图吗

**Comment by CLtheorem** [comment]
> 可以提供下你测试用的蓝图吗


我这任意蓝图都是这种情况，即便保持空白也是painting占据了绝大部分时间

**Comment by huww98** [comment]
那分享下你在chrome performance里录制的trace文件？另外，控制台是否有什么异常的消息？

**Comment by CLtheorem** [comment]
> 那分享下你在chrome performance里录制的trace文件？另外，控制台是否有什么异常的消息？

控制台信息如下
![2024-09-23_220704](https://github.com/user-attachments/assets/fd0f867b-bd49-4a9a-abd4-0ea6c11276af)

这是trace文件

[Trace-20240923T221157.json](https://github.com/user-attachments/files/17098856/Trace-20240923T221157.json)

**Comment by CLtheorem** [comment]
在chrome系统设置中开启图形加速解决了这个问题，chrome就会使用gpu进行渲染了

![2024-10-19_105809](https://github.com/user-attachments/assets/bdb0e9b7-6c95-4169-9b12-64ad52233d27)
