### ISSUE TITLE
行星内物流塔还是3个格子

### ISSUE THREAD

**Issue by NEUGWB** [huww98/dsp_blueprint_editor#2]

**Comment by huww98** [comment]
多谢反馈。我不久前已在 fb6d381bea10f23495a8c15336aa0f38241c41b0 中更新。请在连网时，在页面右下角点击更新，更新到至少v0.2-55

**Comment by NEUGWB** [comment]
可以找个地方显示所需建筑汇总吗，比如整个蓝图包含多少个传送带多少个分拣器这样，光靠肉眼看不出蓝图规模

**Comment by huww98** [comment]
可以考虑。放在加载蓝图后的右边栏，和游戏内类似
________________________________

**Comment by huww98** [comment]
@NEUGWB 已在 c05b450477f690247e737c6a7aa1d927a1930df3 中添加。版本v0.2-57
