### ISSUE TITLE
不能旋转移动视角了

### ISSUE THREAD

**Issue by windivi** [huww98/dsp_blueprint_editor#4]
不能旋转移动视角了，只能远近缩放了。

**Comment by huww98** [comment]
我这测试没有问题。鼠标请使用鼠标中键，与游戏中一样。触屏请使用两个手指。

若还有问题，请提供你的浏览器版本的信息。

**Comment by windivi** [comment]
> 我这测试没有问题。鼠标请使用鼠标中键，与游戏中一样。触屏请使用两个手指。
> 
> 若还有问题，请提供你的浏览器版本的信息。

昂，经验证，我鼠标中键坏了。。。。这真是个悲伤感人的励志故事。

**Comment by shunlibest** [comment]
呜呜，我是是MacOS，用的是触控板，没有鼠标中键。希望可以改成左键拖动

**Comment by huww98** [comment]
> 呜呜，我是是MacOS，用的是触控板，没有鼠标中键。希望可以改成左键拖动

左键拖动我还想保留用于未来的选区功能。加入一个新的触控板模式如何？可以用通常的触控板平移和缩放手势（如blender中的交互）。受限于web API https://github.com/w3c/pointerevents/issues/596 ，暂时还无法自动检测鼠标还是触控板。@shunlibest

**Comment by huww98** [comment]
@shunlibest 对了，你还可以使用键盘wasd

**Comment by shunlibest** [comment]
> 左键拖动我还想保留用于未来的选区功能。加入一个新的触控板模式如何？可以用通常的触控板平移和缩放手势（如blender中的交互）。受限于web API [w3c/uievents#337](https://github.com/w3c/uievents/issues/337) ，暂时还无法自动检测鼠标还是触控板。@shunlibest
感谢回复，我是通过自己拉取代码，修改了对应按键，解决了此问题。

**Comment by shunlibest** [comment]
> > 呜呜，我是是MacOS，用的是触控板，没有鼠标中键。希望可以改成左键拖动
> 
> 左键拖动我还想保留用于未来的选区功能。加入一个新的触控板模式如何？可以用通常的触控板平移和缩放手势（如blender中的交互）。受限于web API [w3c/pointerevents#596](https://github.com/w3c/pointerevents/issues/596) ，暂时还无法自动检测鼠标还是触控板。@shunlibest

感谢回复，我是通过自己拉取代码，修改了对应按键，解决了此问题。
