### ISSUE TITLE
部分建筑增产模式显示不对

### ISSUE THREAD

**Issue by NEUGWB** [huww98/dsp_blueprint_editor#8]
自演化研究站和量子化工厂不显示增产模式，对撞机造反物质显示增产实际只能加速

**Comment by huww98** [comment]
> 自演化研究站和量子化工厂不显示增产模式

应该修好了。

> 对撞机造反物质显示增产实际只能加速

这个我还得核对下游戏里是啥逻辑。

**Comment by NEUGWB** [comment]
一般来说和光子有关的所有产线，除了造白糖都只能加速，用低级建筑造高级建筑只能加速，对撞机造重氢和精炼厂后两个公式只能加速。
还有没有其他建筑不显示或者增产不对还没仔细看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 下午5:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huww98/dsp_blueprint_editor] 部分建筑增产模式显示不对 (Issue #8)




  
自演化研究站和量子化工厂不显示增产模式
  
应该修好了。
  
对撞机造反物质显示增产实际只能加速
  
这个我还得核对下游戏里是啥逻辑。

**Comment by huww98** [comment]
2a21748670f7d20a12be1843464b05595a70c56e 应该能修复该问题。
