### ISSUE TITLE
粘贴蓝图报错 RangeError: Invalid DataView length 107160

### ISSUE THREAD

**Issue by NEUGWB** [huww98/dsp_blueprint_editor#9]
[透镜1800.txt](https://github.com/user-attachments/files/16709367/1800.txt)
游戏里可以正常粘贴

**Comment by huww98** [comment]
Fixed in 5b1a2588243a9bf7115c00ede4757aa42e719dbe

蓝图中加入了新的倾斜传送带相关参数。本程序暂未支持倾斜传送带的渲染，仅修复了解析错误
